2018-05-03 21:43:36.909516: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-05-03 21:43:38.072127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:04:00.0
totalMemory: 11.92GiB freeMemory: 11.80GiB
2018-05-03 21:43:38.072159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:04:00.0, compute capability: 5.2)
WARNING::lambda1_stud not found in config file
WARNING::lambda2_stud not found in config file
2018-05-03 21:43:38.160566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:04:00.0, compute capability: 5.2)
Load 50000 samples.
Load 10000 samples.
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    model.load_model(load_dir)
  File "/users/hzhang2/haowen/GitHub/autoLoss/models/gan.py", line 343, in load_model
    raise Exception('Invalid checkpoint_dir: ' + checkpoint_dir)
Exception: Invalid checkpoint_dir: /datasets/BigLearning/haowen/autoLoss/saved_models/dcgan_pretrain
