WARNING::lambda1_stud not found in config file
WARNING::lambda2_stud not found in config file
2018-05-10 12:40:17.314643: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-05-10 12:40:18.218985: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:04:00.0
totalMemory: 11.92GiB freeMemory: 11.80GiB
2018-05-10 12:40:18.219014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:04:00.0, compute capability: 5.2)
init_mnist_model
Extracting /datasets/BigLearning/haowen/mnist/train-images-idx3-ubyte.gz
Extracting /datasets/BigLearning/haowen/mnist/train-labels-idx1-ubyte.gz
Extracting /datasets/BigLearning/haowen/mnist/t10k-images-idx3-ubyte.gz
Extracting /datasets/BigLearning/haowen/mnist/t10k-labels-idx1-ubyte.gz
Load 55000 samples.
Extracting /datasets/BigLearning/haowen/mnist/train-images-idx3-ubyte.gz
Extracting /datasets/BigLearning/haowen/mnist/train-labels-idx1-ubyte.gz
Extracting /datasets/BigLearning/haowen/mnist/t10k-images-idx3-ubyte.gz
Extracting /datasets/BigLearning/haowen/mnist/t10k-labels-idx1-ubyte.gz
Load 10000 samples.
Traceback (most recent call last):
  File "trainer.py", line 17, in <module>
    from models import gan
  File "/users/hzhang2/haowen/GitHub/autoLoss/models/gan.py", line 14, in <module>
    from utils import inception_score_mnist
  File "/users/hzhang2/haowen/GitHub/autoLoss/utils/inception_score_mnist.py", line 56, in <module>
    _init_mnist_model()
  File "/users/hzhang2/haowen/GitHub/autoLoss/utils/inception_score_mnist.py", line 53, in _init_mnist_model
    mnist_model.load_model(checkpoint_dir)
  File "/users/hzhang2/haowen/GitHub/autoLoss/models/basic_model.py", line 45, in load_model
    raise Exception('Invalid checkpoint_dir: ' + checkpoint_dir)
Exception: Invalid checkpoint_dir: /datasets/BigLearning/haowen/autoLoss/saved_models/mnist_classification
